Removed UnusedPrivateElements
doctrine/coding-standard pull request #235
Opened 2020-12-24 14:41 UTC by stephanvierkant

It has been removed from Slevomat: https://github.com/slevomat/coding-standard/commit/bcbf756f05979a05b1ae2b7a8ed6796f060cfa83

2020-12-26 00:16 UTC, SenseException requested changes
@stephanvierkant You also need to adapt the tests that covers this ruke.

2020-12-29 13:31 UTC, stephanvierkant commented
I changed the tests, but they still fail with PHP 7.4. Any idea how to fix them?

2021-01-04 17:56 UTC, SenseException commented
@stephanvierkant The `Makefile` is running a task that [merges a patch](https://github.com/doctrine/coding-standard/blob/8.2.x/tests/php-compatibility.patch) for PHP 7.4. The patching seems to fail because of the introduced changes. You can try to run that patch from the `test-report` task in the Makefile on your local machine in a outside of your developer branch to check what is causing the conflict and what can be done to make the patch work again.

2021-02-21 18:38 UTC, morozov commented
See https://github.com/doctrine/coding-standard/pull/237.

2021-02-21 18:44 UTC, closed without merging