feat: enable parent call spacing
doctrine/coding-standard pull request #291
Opened 2022-09-20 21:25 UTC by simPod

2022-09-20 22:07 UTC, morozov approved these changes

2022-09-20 22:08 UTC, Ocramius approved these changes

2022-09-21 00:10 UTC, ostrolucky requested changes
I don't think this one is worth it

2022-09-21 06:17 UTC, greg0ire approved these changes
[We seem inconsistent regarding this](https://github.com/doctrine/orm/search?p=1&q=parent), I think it's good we normalize it.

2022-09-21 08:44 UTC, ostrolucky approved these changes
Alright then. I'm not going to block this if most people want this.

2022-09-21 09:48 UTC, lcobucci approved these changes

2022-09-21 09:48 UTC, merged